name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v2
        with:
          verbosity: Diagnostic
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TORWLaunchpad.dll
          path: TORWLaunchpad/LaunchpadReloaded/bin/Debug/net6.0/TORWLaunchpad.dll
      - name: List build output
        run: ls -R TORWLaunchpad/LaunchpadReloaded/bin/Debug/net6.0
